SELECT EMPLOYEE.EMPLOYEENAME, EMPLOYEE.EMPLOYEESURNAME, EMPLOYEE.SALARY
FROM EMPLOYEE
INNER JOIN UNITS ON EMPLOYEE.EMPLOYEUNITID = UNITS.ID
WHERE UNITS.UNITNAME = 'yazılım' OR UNITS.UNITNAME = 'donanım';
