SELECT E.EMPLOYEENAME, E.EMPLOYEESURNAME, U.UNITNAME, T.TITLEEMPLOYE, B.BONUSWAGE
FROM EMPLOYEE E
INNER JOIN UNITS U ON E.EMPLOYEUNITID = U.ID
INNER JOIN TITLE T ON E.ID = T.EMPLOYETITLEID
INNER JOIN BONUS B ON E.ID = B.EMPLOYEBONUSID
WHERE B.BONUSWAGE IS NOT NULL;
