CREATE TABLE UNITS
(
    ID INT PRIMARY KEY NOT NULL,
    UNITNAME NVARCHAR(50) NOT NULL
)
CREATE TABLE EMPLOYEE
(
	ID INT PRIMARY KEY NOT NULL,
	EMPLOYEENAME NVARCHAR NOT NULL,
	EMPLOYEESURNAME NVARCHAR NULL,
	SALARY DECIMAL(12,2) NULL,
	JOINDATE DATETIME NOT NULL,
	EMPLOYEUNITID INT NOT NULL
    FOREIGN KEY (EMPLOYEUNITID) REFERENCES UNITS(ID)
)
CREATE TABLE BONUS
(
    EMPLOYEBONUSID INT NOT NULL,
    BONUSWAGE INT NOT NULL,
    BONUSDATE DATETIME NOT NULL
    FOREIGN KEY (EMPLOYEBONUSID) REFERENCES EMPLOYEE(ID)
)
CREATE TABLE TITLE
(
    EMPLOYETITLEID INT NOT NULL,
    TITLEEMPLOYE NVARCHAR(50) NOT NULL,
    TITLEDATE DATETIME NOT NULL
    FOREIGN KEY (EMPLOYETITLEID) REFERENCES EMPLOYEE(ID)
)